version: '3.8'

services:
  # --------------------------------------------------
  # for development
  # --------------------------------------------------

  backend:
    build:
      dockerfile: ./.docker/backend/Dockerfile
      context: ./
    # command: npm run start:dev
    command: npm run start:debug
    volumes:
      - ./:/app:delegated
      - backend-nodemodules-volume:/app/node_modules/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${_DOCKER_COMPOSE_HOST_PORT_BACKEND:-13011}:3000 # for nestjs
      - ${_DOCKER_COMPOSE_HOST_PORT_BACKEND_DEBUG:-19229}:9229 # for debug

  db:
    image: mysql:8.0.32
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    ports:
      - '${_DOCKER_COMPOSE_HOST_PORT_BACKEND:-13316}:3306'
    volumes:
      - ./.docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-volume:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 10
      timeout: 100s

  # --------------------------------------------------
  # commands
  # --------------------------------------------------

  schemaspy:
    image: schemaspy/schemaspy:6.2.4
    platform: linux/x86_64
    user: root
    volumes:
      - ./.docker/schemaspy/schemaspy.properties:/schemaspy.properties # SchemaSpy Properties File
      - ./doc/definition/db:/output # SchemaSpy Output dir
    depends_on:
      - db
    environment:
      SCHEMASPY_OUTPUT: /output
    profiles:
      - schemaspy

volumes:
  db-volume:
  backend-nodemodules-volume:
